### ISSUE TITLE
Question about: RUN apt-get -y install rsync (and other apps)

### ISSUE THREAD

**Issue by pascalandy** [phusion/baseimage-docker#296]
Hey guys,

Here is my Dockerfile

```
FROM phusion/baseimage:0.9.18

    # Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

    # svn details http://goo.gl/NNWBJK
RUN apt-get update && apt-get -y install rsync git subversion wget zip unzip

    # Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```
I bash into the container:

$ docker exec -it phusion bash

When I want to use rsync command the system answers:

> bash: sudo: command not found

So I'm want to check via:

$ apt-cache policy rsync
> N: Unable to locate package rsync

Well well !!!??

Let's install it from here:

$ apt-get update && apt-get -y install rsync

It works! [See](https://gist.github.com/pascalandy/bf3f9fc99dbbb1dea997b4039e83ad64)

So why the apps are not installed when I create the container ??

Thank you in advance and goooooodd job about this while project/philosophy :)

Cheers!
Pascal

**Comment by erikj** [comment]
Have you built an image from the `Dockerfile`? If not, you'll need to do so, and then run a container from that image, _e.g._:

```sh
$ docker build -t pascalandy/baseimage .
$ docker run -it pascalandy/baseimage bash
```

**Comment by pascalandy** [comment]
Hello Eric,

I just did it.
`devmtl/phusion:0.9.18`

But I have to same behavior :((

Here is my turnaround which in not clean and take about 60 sec to build

```
phusion:
  image: devmtl/phusion:0.9.18
  container_name: phusion
  volumes:
    - ./app/volumes/content:/var/lib/app
  working_dir: /var/lib/
  command: sh -c 'apt-get update && apt-get upgrade -y && apt-get install -y rsync git && cd /var/lib/ && ls -la && git clone https://github.com/user/somerepo.git tmp-themes && rsync -zvrh --delete /var/lib/tmp-themes/ /var/lib/prod && rm -r tmp-themes'
```
