### ISSUE TITLE
Missing link environment variables

### ISSUE THREAD

**Issue by javereec** [phusion/baseimage-docker#32]
It looks like the environment variables set when linking a container are not available when using your image. Information on the docker site:

http://docs.docker.io/en/latest/use/working_with_links_names/

I use these in my rails app container database.yml script.

e.g.

``` yaml
defaults: &defaults
  adapter: postgresql
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] %>
  username: docker
  password: docker

development:
  <<: *defaults
  database: db_development

test:
  <<: *defaults
  database: db_test

production:
  <<: *defaults
  database: db_production
```
